# Generated by Django 5.2.9 on 2026-01-04 09:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api_test", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="automationcasetestresult",
            new_name="api_test_au_automat_71c7cb_idx",
            old_fields=("automationCaseApi", "testTime"),
        ),
    ]
