# Generated by Django 4.2.30 on 2026-07-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "api_test",
            "0002_rename_automationcasetestresult_automationCaseApi_testTime_api_test_au_automat_71c7cb_idx",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="apiresponse",
            name="tier",
            field=models.CharField(
                blank=True, default="", max_length=2048, verbose_name="层级路径"
            ),
        ),
    ]
